### 헬스 체크
GET http://localhost:8080/health-check

### 회원 가입
POST http://localhost:8080/v1/users/sign-up
Content-Type: application/json
Authorization: Bearer 

{
  "grade": "M1",
  "term": 1,
  "lastSubjectUnitId": 1,
  "studyHours": 1.0,
  "workbooks": ["쎈 중등수학 1-1"]
}

### 닉네임 변경
PATCH http://localhost:8080/v1/users/me/nickname
Content-Type: application/json
Authorization: Bearer

{
  "nickname": "정다은1"
}

### 유저 정보 조회
GET http://localhost:8080/v1/users/me
Authorization: Bearer

### 유저 정보 수정
PUT http://localhost:8080/v1/users/me
Content-Type: application/json
Authorization: Bearer

{
	"nickname": "황수민",
	"grade": "M3",
	"term": 2
}